name: First workflow

on:
  push:
    branches: [main]


jobs:
  # test:
  #   name: Run-tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 
  #       users: 

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/path/to/your/server/directory"  # Путь на сервере, куда копировать файлы

    - name: Restart Telegram bot service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop telegram-bot  # Остановка сервиса
          sudo systemctl start telegram-bot  # Запуск сервиса заново