name: First workflow

on:
  push:
    branches: [main]


jobs:
  # test:
  #   name: Run-tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 
  #       users: 

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami

    # - name: Pull updates to server
    #   uses: D3rHase/ssh-command-action@v0.2.2
    #   with:
    #     host: ${{secrets.SSH_HOST}}
    #     user: ${{secrets.SSH_USER}}
    #     private_key: ${{secrets.SIZIF_SSH_KEY}}
    #     command: |
    #       cd ${{secrets.PROJECT_FOLDER}}
    #       git pull
    #       sudo systemctl restart keretao_bot.service
            